
sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - npm install

services:
  - docker

script:
  - ng version
  - ng build --prod -c production
#  - ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
#  - ng e2e --port=4100

deploy:
  - provider: script
    script: bash docker/docker.sh
    skip_cleanup: true
    on:
      all_branches: true

notifications:
  on_success: change # default: always
  on_failure: always
  slack: lbryians:CRmGI1lcH27T7owdedmuEmRQ
